"""
HTML generator for Section: Comparison with GuidedTTS 2.
"""

from dominate.tags import *
from .templates.audios import audio_table
from .templates.spinspy import nav_spin


def section_guidedtts2_compare():
    # Compare with GuidedTTS 2 Audio Samples:
    h3("Extra: Comparison with GuidedTTS 2")
    p(
        [
            """In this section, we compare our model with""",
            a("""Guided TTS 2""", href="https://arxiv.org/abs/2205.15370"),
            """ by comparing samples obtained from """,
            a("its demo page", href="https://ksw0306.github.io/guided-tts2-demo/"),
            ". GuidedTTS 2 samples are downsampled to 16kHz for comparison. ",
            """Compared with our work, GuidedTTS 2 is trained on a much larger dataset, and it does not require transcriptions of the source audios."""
            "the transcription of the source audios."
        ], _class="lead"
    )
    blocks = []
    def _gen_table(short: str, long: str, text: str):
        return audio_table(
            text=text,
            audio_files=[
                f"/diffvoice-web/samples/compare_guidedtts2/{short}_{sys}.wav" for sys in (
                    "ref", "diffvoice", "guidedtts2_zeroshot", "guidedtts2_finetune",
                )
            ],
            titles=[
                f"Reference ({long})", "DiffVoice(Zero-shot)", "GuidedTTS2(Zero-shot)", "GuidedTTS2(Fine-tune)"
            ],
            width=4, control_width_px=250
        )

    blocks.append(_gen_table("steve", "Steve Jobs",
        "Transcript: " + """This audio was generated by a text-to-speech model for Steve Jobs. We use ten second untranscribed speech from Steve Jobs’ Stanford Commencement Address."""
    ))
    blocks.append(_gen_table("heung", "Heung-min Song",
        "Transcript: " + """This audio was generated by a text-to-speech model for Sonny. We propose Guided Text-to-Speech 2, a diffusion based generative model for high-quality adaptive text-to-speech using untranscribed data."""
    ))
    blocks.append(_gen_table("emma", "Emma Watson",
        "Transcript: " + """This audio was generated by a text-to-speech model for Emma Watson. We found that the gap between the zero shot approach and the finetune approach is quite large in the case of real world data."""
    ))
    blocks.append(_gen_table("LJ002-0185", "LJ002-0185",
        "Transcript: " + """There was unrestrained association of untried and convicted, juvenile with adult prisoners, vagrants, misdemeanants, felons."""
    ))
    blocks.append(_gen_table("LJ029-0212", "LJ029-0212",
        "Transcript: " + """Nor did the methods by which they were perpetrated greatly vary from those in times past."""
    ))
    blocks.append(_gen_table("LJ017-0244", "LJ017-0244",
        "Transcript: " + """He was struck with the appearance of the corpse, which was not emaciated, as after a long disease ending in death;"""
    ))
